SOURCE_PROPERTIES = 'properties'
SOURCE_RUNTIME_PROPERTIES = 'runtime_properties'
SOURCE_INPUTS = 'inputs'
SOURCE_RESOLVE = 'resolve'

SOURCE_SOURCE_PROPERTIES = 'source_properties'
SOURCE_SOURCE_RUNTIME_PROPERTIES = 'source_runtime_properties'
SOURCE_TARGET_PROPERTIES = 'target_properties'
SOURCE_TARGET_RUNTIME_PROPERTIES = 'target_runtime_properties'

SOURCES_DEFAULT_ORDER = [
    SOURCE_PROPERTIES,
    SOURCE_RUNTIME_PROPERTIES,
    SOURCE_INPUTS,
    SOURCE_RESOLVE
]

API_CTX = 'api_ctx'
PROPERTY_API_CONFIGS = 'api_configs'
