SOURCE_PROPERTIES = 'properties'
SOURCE_RUNTIME_PROPERTIES = 'runtime_properties'
SOURCE_INPUTS = 'inputs'
SOURCE_RESOLVE = 'resolve'
SOURCES_DEFAULT_ORDER = [
    SOURCE_PROPERTIES,
    SOURCE_RUNTIME_PROPERTIES,
    SOURCE_INPUTS,
    SOURCE_RESOLVE
]
API_CTX = 'api_ctx'
PROPERTY_API_CONFIGS = 'api_configs'
